prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

grafana:
  service:
    type: ClusterIP
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: lucidity
      alb.ingress.kubernetes.io/group.order: "10"
      alb.ingress.kubernetes.io/healthcheck-path: /grafana/api/health
    path: /grafana
    pathType: Prefix
  sidecar:
    dashboards:
      searchNamespace: ALL

alertmanager:
  enabled: true

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
